# Generated by Django 3.0.7 on 2020-06-18 22:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Número de telefone deve ter o formato: '+999999999'. Máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.Especialidade')),
            ],
        ),
    ]
