# Generated by Django 3.0.7 on 2020-06-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_auto_20200621_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
